Repository kids-first/kf-annotation-tools, pull requests merged in 2024-02, with the labels that each got.

#4 ✨ Echtvar Update
  docs/CUSTOM_GNOMAD_REF.md
  docs/gnomad_update.json
  tools/bcftools_annotate.cwl
  tools/bcftools_strip_ann.cwl
  tools/echtvar_anno.cwl
  tools/gatk_variant_filter.cwl
  tools/kf_mskcc_vcf2maf.cwl
  workflows/kfdrc-germline-snv-annot-workflow.cwl
Labels: documentation, bix-dev

#2 :robot: new gha for submodule updating
  .github/workflows/release_submodule_updater.yml
Labels: feature, bix-dev

#10 🐛 fix github ref name
  .github/workflows/release_submodule_updater.yml
Labels: bug, bix-dev
